name: CI

on:
  push:
  release:
    types: [published]

jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v1
        with:
          fetch-depth: 50
      - name: Build Docker Image
        run: make build-app-image
      - name: Publish Docker Image (on release only)
        if: github.event_name == 'release' && startsWith(github.ref, 'refs/tags')
        run: |
          echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
          make publish-app-image
